### ISSUE TITLE
文件匹配异常，把不是链接的内容识别为了链接

### ISSUE THREAD

**Issue by toweringx** [pondered/hexo-obsidian-backlink#1]
![image](https://user-images.githubusercontent.com/60003281/224728638-019252c7-d109-47b2-a4de-64f4482a336e.png)
![image](https://user-images.githubusercontent.com/60003281/224728745-2b35f6ca-a4da-4194-8320-a087dd4040d5.png)
哈喽，你好，最近我正好在整合Obsidian 和 hexo，在使用这个hexo插件的时候发现在文本内有如上内容的时候会报匹配错误，我看了一下源代码，发现是根据  [[]] 来做的匹配，这种匹配模式在上述情况下会错误的将文本视作需要链接的文件。在这个匹配规则里添加内部文本是否带有文件后缀的校验是否可以在一定程度上解决这类问题，当然这只是我的初步想法，希望和大佬一起交流学习一下。

**Comment by yolo079** [comment]
你好,
请问这个插件怎么用哦
有没有使用说明的链接学习学习.

**Comment by pondered** [comment]
> ![image](https://user-images.githubusercontent.com/60003281/224728638-019252c7-d109-47b2-a4de-64f4482a336e.png)
> 
> ![image](https://user-images.githubusercontent.com/60003281/224728745-2b35f6ca-a4da-4194-8320-a087dd4040d5.png)
> 
> 哈喽，你好，最近我正好在整合Obsidian 和 hexo，在使用这个hexo插件的时候发现在文本内有如上内容的时候会报匹配错误，我看了一下源代码，发现是根据  [[]] 来做的匹配，这种匹配模式在上述情况下会错误的将文本视作需要链接的文件。在这个匹配规则里添加内部文本是否带有文件后缀的校验是否可以在一定程度上解决这类问题，当然这只是我的初步想法，希望和大佬一起交流学习一下。

这样和obsidian的语法冲突了，我加一个有没有换行的判断吧

**Comment by pondered** [comment]
> 你好,
> 
> 请问这个插件怎么用哦
> 
> 有没有使用说明的链接学习学习.

这个是 obsidian 的md 转hexo的插件 所以你直接用那两个就可以了

**Comment by pondered** [comment]
> 你好,
> 
> 请问这个插件怎么用哦
> 
> 有没有使用说明的链接学习学习.

就一个文件 直接看就可以了
