### ISSUE TITLE
页面内跳转匹配问题

### ISSUE THREAD

**Issue by qiwuteng** [pondered/hexo-obsidian-backlink#2]
你好，对于这样的也没内跳转形式 `[跳转到标题1](#标题1)` 会导致error，能否解决一下，Thanks♪(･ω･)ﾉ

**Comment by pondered** [comment]
> 你好，对于这样的也没内跳转形式 `[跳转到标题1](#标题1)` 会导致error，能否解决一下，Thanks♪(･ω･)ﾉ

好的我去试一下看能不能复现

**Comment by pondered** [comment]
我这边没有复现这个问题 @qiwuteng
